services:
  app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    stop_signal: SIGINT  # required to stop gracefully
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
